Controllers/Driver/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using BE = FutureTransportEntities.BusinessEntities;
using BL = FutureTransportBuisenessLayer.Driver;
using System.Data;
using FutureTransport.Filters;

namespace FutureTransport.Controllers.Driver
{
    [UserAuthenticationFilter]
    public class DriverController : Controller
    {
        BL.DriverDataProvider DataProvider = new BL.DriverDataProvider();
        public ActionResult DriverRegistration()
        {
            return View(); 
        }

        [HttpPost]
        public ActionResult AttachmentDriverRegistration()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AjaxUploadDriverLicense(BE.DriverLicense fileData)
        {
            BE.DriverLicense driverLicense = new BE.DriverLicense();
            if (Request.Files.Count > 0)
            {
                try
                {
                    int Userid = Convert.ToInt16(Session["UserId"]);
                    string Type = fileData.EnqType;
                    Type = Type + Userid;
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {

                        HttpPostedFileBase file = files[i];
                        string fname;
                        string root = Server.MapPath("~/Uploads/DriverLicense/" + Type + "/");
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }
                        string contentType;
                        contentType = MimeMapping.GetMimeMapping(fname);

                        if (!Directory.Exists(root))
                        {
                            Directory.CreateDirectory(root);
                        }
                        string check = Path.Combine(Server.MapPath("~/Uploads/DriverLicense/" + Type + "/"), fname);
                        if (System.IO.File.Exists(fname))
                        {
                            System.IO.File.Delete(fname);
                        }
                        file.SaveAs(check);
                        driverLicense.DocName = fname;
                        driverLicense.FilePath = check;
                        driverLicense.ContentType = contentType;
                    }
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            return Json(driverLicense);
        }

        [HttpPost]
        public ActionResult StoreFileDataInTemp(string DocName, string Filepath, string ContentType)
        {
            TempData["DocName"] = DocName;
            TempData["Filepath"] = Filepath;
            TempData["ContentType"] = ContentType;
            int i = 1;
            return Json(i);
        }

        public FileResult DownloadFile(int id)
        {
            string DocName = Convert.ToString(TempData["DocName"]);
            string Filepath = Convert.ToString(TempData["Filepath"]);
            string ContentType = Convert.ToString(TempData["ContentType"]);
            byte[] fileBytes = System.IO.File.ReadAllBytes(Filepath);
            return File(fileBytes, ContentType, DocName);
        }

        public JsonResult AjaxDriverRegistration(BE.Drivers DD, List<BE.DriverLicense> A)
        {
            DD.AddedBy = Convert.ToInt16(Session["UserId"]);
            List<BE.Drivers> drivers = new List<BE.Drivers>();
            drivers = DataProvider.DriverRegistration(DD);

            if (A != null)
            {
                for (int j = 0; j < A.Count; j++)
                {
                    string root = Server.MapPath("~/Uploads/DriverLicenseAttachment/DriverLicenseFor" + drivers[0].DriverNo + "/");
                    if (!Directory.Exists(root))
                    {
                        Directory.CreateDirectory(root);
                    }
                    string oldPath = A[j].FilePath;
                    string newPath = Path.Combine(Server.MapPath("~/Uploads/DriverLicenseAttachment/DriverLicenseFor" + drivers[0].DriverNo + "/"), A[j].DocName);
                    if (!System.IO.File.Exists(newPath))
                    {
                        System.IO.File.Move(oldPath, newPath);

                    }

                    A[j].FilePath = newPath;
                }
            }
            if (A != null)
            {
                DataTable dataTable = new DataTable();
                dataTable.Columns.Add("DocId");
                dataTable.Columns.Add("DriverNo");
                dataTable.Columns.Add("UploadFor");
                dataTable.Columns.Add("DocName");
                dataTable.Columns.Add("FilePath");
                dataTable.Columns.Add("ContentType");
                dataTable.TableName = "PT_DriverLicenseAttachment";
                foreach (BE.DriverLicense item in A)
                {
                    DataRow row = dataTable.NewRow();
                    row["DocId"] = item.DocId;
                    row["DriverNo"] = drivers[0].DriverNo;
                    row["UploadFor"] = item.UploadFor;
                    row["DocName"] = item.DocName;
                    row["FilePath"] = item.FilePath;
                    row["ContentType"] = item.ContentType;
                    dataTable.Rows.Add(row);
                }
                string message = DataProvider.SaveAttachment(dataTable, DD.AddedBy);
            }
            return Json(drivers);
        }

        public JsonResult GetDrivers()
        {
            List<BE.Drivers> list = new List<BE.Drivers>();
            list = DataProvider.GetDrivers();
            return Json(list);
        }
    }
}

Views/Driver/AttachmentDriverRegistration.cshtml
<div>
    <div class="modal-header">
        <h5 class="modal-title">Driver License Attachments</h5>
        <label id="MSNoFile" style="visibility:hidden"></label>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form>
            <div class="form-group">
                <input type="file" id="fileLicenseAttachment" name="postedFile" />
                <input type="Button" class="btn btn-primary" id="btnUpload" value="Upload"/>
            </div>
            <div class="form-group">
                <div class="table-responsive">
                    <table id="licenseAttachmentTable" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="wd-15p sorting">File Name</th>
                                <th style="width:15px"></th>
                                <th style="width:15px"></th>
                            </tr>
                        </thead>
                        <tbody style="box-sizing :border-box;"></tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button class="btn btn-info pull-right" id="btnDone" data-dismiss="modal" aria-label="Close">Done</button>
    </div>
</div>

@using (Html.BeginForm("DownloadFile", "Driver", FormMethod.Post))
{
    <input type="hidden" id="hiddenFile" name="id" />
    <button type="submit" class="btn btn-primary" id="btnDownload" style="display:none">Download</button>
}

<script>
    var type = 'DriverLicense';
    var table = [];

    $(document).ready(function () {
        $('#licenseAttachmentTable').dataTable({
            "bLengthChange": false,
            "bInfo": false,
            "bPaginate": false,
            "bFilter": false,
            "paging": false
        });

        table = licenseAttachment;

        if (table.length != 0) {
            $('#licenseAttachmentTable').dataTable({
                "bLengthChange": false,
                "bInfo": false,
                "bPaginate": false,
                "bFilter": false,
                "paging": false,
                "destroy": true,
                "bLengthChange": false,
                "aaData": table,
                "columns": [
                    { "data": "DocName" },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningID + ')"><i class="fa fa-download"></i></a>';
                            }
                            return data;
                        }
                    },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningID + ')"><i class="fa fa-trash-o"></i></a>';
                            }
                            return data;
                        }
                    }
                ]
            });
            countRows();
        }
    });

    $(document).ready(function () {
        $('#btnUpload').click(function () {
            var MSNoFile1 = "";
            
            if (window.FormData !== undefined) {

                var fileUpload = $("#fileLicenseAttachment").get(0);
                var files = fileUpload.files;
                var fileData = new FormData();

                if (files.length == 0) {
                    alert("Please select file!")
                    return false;
                }
                else {
                    addAttachmentA(type);
                }
            }
            else {
                alert("FormData is not supported");
            }
        });
    });

    function addAttachmentA(data) {
        $("#global-loader").fadeIn("slow");
        var fileUpload = $("#fileLicenseAttachment").get(0);
        var files = fileUpload.files;
        var fileData = new FormData();
        var UploadType = data;

        var iSize = document.getElementById('fileLicenseAttachment').files[0].size / 1024
        iSize = (Math.round((iSize / 1024) * 100) / 100)

        if (iSize > 25) {
            alert("Selected file size more than 25 MB");
            $("#global-loader").fadeOut("slow");
            return false;
        }

        for (var i = 0; i < files.length; i++) {
            fileData.append(files[i].name, files[i]);
        }
        fileData.append('EnqType', UploadType);
        runningNo++;

        $.ajax({
            url: '/Driver/AjaxUploadDriverLicense',
            type: "POST",
            contentType: false, 
            processData: false, 
            data: fileData,
            success: function (Data) {
                $("#global-loader").fadeOut("slow");
                var element = {};
                element.DocName = Data.DocName;
                element.RunningID = runningNo;
                element.FilePath = Data.FilePath;
                element.ContentType = Data.ContentType;
                element.UploadType = type;
                licenseAttachment.push(element);
                table = licenseAttachment;

                $('#licenseAttachmentTable').dataTable({
                    "bLengthChange": false,
                    "bInfo": false,
                    "bPaginate": false,
                    "bFilter": false,
                    "paging": false,
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": table,
                    "columns": [
                        { "data": "DocName" },
                        {
                            "data": "FilePath",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningID + ')"><i class="fa fa-download"></i></a>';
                                }
                                return data;
                            }
                        },
                        {
                            "data": "ContentType",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningID + ')"><i class="fa fa-trash-o"></i></a>';
                                }
                                return data;
                            }
                        }
                    ]
                });
                countRows();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
                console.log(errormessage.responseText)
                $("#global-loader").fadeOut("slow");
            }
        });
        $("#fileLicenseAttachment").val('');
    }

    function downloadAttachment(runningNo) {
        var no = runningNo;
        var docname, Filepath, contentType;
        for (i = 0; i < table.length; i++) {
            if (table[i].RunningID == no) {
                docname = table[i].DocName;
                Filepath = table[i].FilePath;
                contentType = table[i].ContentType;
            }
        }
        var id = 0;
        var data = { 'DocName': docname, 'Filepath': Filepath, 'ContentType': contentType }
        data = JSON.stringify(data);

        $.ajax({
            url: '/Driver/StoreFileDataInTemp',
            type: "POST",
            contentType: "application/json; charset=utf-8",
            data: data,
            success: function (Data) {
                id = Data;
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
        $("#hiddenFile").val(id);
        $("#btnDownload")[0].click();
    }

    function deleteAttachment(id) {
        var r = confirm("Are you sure want to delete this file!");
        if (r == true) {
            var no = id;
            for (i = 0; i < table.length; i++) {
                if (table[i].RunningID == no) {
                    table.splice(i, 1);
                }
            }
            $('#licenseAttachmentTable').dataTable({
                "bLengthChange": false,
                "bInfo": false,
                "bPaginate": false,
                "bFilter": false,
                "paging": false,
                "destroy": true,
                "bLengthChange": false,
                "aaData": table,
                "columns": [
                    { "data": "DocName" },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningID + ')"><i class="fa fa-download"></i></a>';
                            }
                            return data;
                        }
                    },
                    {
                        "data": "ContentType",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningID + ')"><i class="fa fa-trash-o"></i></a>';
                            }
                            return data;
                        }
                    }
                ]
            });
            countRows();
        }
    }

    function countRows() {
        var table = $('#licenseAttachmentTable').DataTable();
        var RowCount = table.rows().count();
        document.getElementById('lblAttachment').innerHTML = RowCount;
    }
</script>

Views/Driver/DriverRegistration.cshtml
@{
    ViewBag.Title = "Driver Registration";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="DriverEntry">
    <div class="page-header">
        <h4 class="page-title">Driver Registration</h4>
        <button class="btn btn-primary" title="Summary" data-toggle="tooltip" data-placement="bottom" onclick="ShowSummary()"><i class="fa fa-file"></i></button>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="form-group">
                <div class="col-4">
                    <label class="form-label mt-1">Name :</label>
                </div>
                <div class="col-4">
                    @Html.TextBox("Name", null, new { @class = "form-control", @id = "name", name = "name", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-4">
                    <label class="form-label mt-1">DOB :<i class="fa fa-calendar"></i></label>
                </div>
                <div class="col-4">
                    @Html.TextBox("DOB", null, new { @class = "form-control datePicker", @id = "dob", name = "dob", @Value = DateTime.Now.ToString("dd MMM yyyy") })
                </div>
            </div>

            <div class="form-group">
                <div class="col-4">
                    <label class="form-label mt-1">License No :</label>
                </div>
                <div class="col-4">
                    @Html.TextBox("LicenseNo", null, new { @class = "form-control", @id = "licenseNo", name = "licenseNo", autocomplete = "off" })
                </div>
            </div>

            <div class="col-sm-12 col-lg-3 col-md-3">
                <div class="form-group">
                    <div class="row gutters-xs">
                        <div class="col">
                            <a href="#" onclick="addAttachment()">
                                <i class="fa fa-paperclip fa-2x	" style="color:#070884" aria-hidden="true" title="Upload Attachments"></i>
                                <span class="custom-switch-description" style="font-size:17px;color:#6c4cbb"><b><label id="lblAttachment">0</label></b></span>
                            </a>
                        </div>
                    </div>
                    <label class="form-label">Upload Attachments</label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-4">
                    <label class="form-label mt-1">Mobile :</label>
                </div>
                <div class="col-4">
                    @Html.TextBox("Mobile", null, new { @class = "form-control", @id = "mobile", name = "mobile", autocomplete = "off" })
                </div>
            </div>

            <div class="form-group">
                <div class="col">
                    <button class="btn btn-success" title="Save" data-toggle="tooltip" data-placement="bottom" onclick="driverRegistration()"><i class="fa fa-save"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="DriverSummary">
    <div class="page-header">
        <h4 class="page-title">Driver Summary</h4>
        <button class="btn btn-primary" title="Back" data-toggle="tooltip" data-placement="bottom" onclick="ShowEntry()"><i class="fa fa-arrow-left"></i></button>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="th_Background table table-striped table-bordered text-center text-nowrap" style="width:100%" id="tblSummary">
                    <thead class="bg-primary">
                        <tr>
                            <th>Driver Name</th>
                            <th>Date of Birth</th>
                            <th>License Number</th>
                            <th>Mobile Number</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="licenseModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content" id='licenseModalContent'></div>
    </div>
</div>

<script>
    var DocId = 0;
    var DriverNo = "0";
    var runningNo = 1;
    var licenseAttachment = [];
    var licenseAttachment;
    var totalAttchment = [];
    var masterAttachment = [];

    $(document).ready(function () {
        Load();
        $("#DriverSummary").hide();
    });

    $( function() {
        $(".datePicker").datepicker({
            autoclose: true,
            todayHighlight: true,
            format: 'dd M yyyy',
            language: "tr",
            changeMonth: true,
            changeYear: true,
        });
    });

    function addAttachment() {
        $.ajax({
            type: "POST",
            url: "/Driver/AttachmentDriverRegistration",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                $('#licenseModalContent').html(response);
                $('#licenseModal').modal('show');
            },
            failure: function (response) {
                alert(response);
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        })
    }

    function driverRegistration() {
        var basicElement = {};
        basicElement.DocId = DocId;
        basicElement.DriverNo = DriverNo;
        basicElement.DriverName = $("#name").val();
        basicElement.DOB = $("#dob").val();
        basicElement.LicenseNo = $("#licenseNo").val();
        basicElement.MobileNo = $("#mobile").val();

        if (basicElement.DriverName == "") {
            Swal.fire({
                title: 'Error',
                text: "Please Enter the Name",
                icon: 'error'
            });
            return false;
        }
        if (basicElement.DOB == "") {
            Swal.fire({
                title: 'Error',
                text: "Please Enter the Date Of Birth",
                icon: 'error'
            });
            return false;
        }
        if (basicElement.LicenseNo == "") {
            Swal.fire({
                title: 'Error',
                text: "Please Enter the License Number",
                icon: 'error'
            });
            return false;
        }
        if (basicElement.MobileNo == "") {
            Swal.fire({
                title: 'Error',
                text: "Please Enter the Mobile Number",
                icon: 'error'
            });
            return false;
        }

        totalAttchment = licenseAttachment;
        for (i = 0; i < totalAttchment.length; i++) {
            var element = {};
            element.UploadFor = "Driver License";
            element.DocName = totalAttchment[i].DocName;
            element.FilePath = totalAttchment[i].FilePath;
            element.ContentType = totalAttchment[i].ContentType;
            masterAttachment.push(element);
        }

        var data = { 'DD': basicElement, 'A': masterAttachment };
        data = JSON.stringify(data);

        $.ajax({
            type: 'post',
            url: '/Driver/AjaxDriverRegistration',
            data: data,
            async: false,
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                if (response.Status != 0) {
                    Swal.fire({
                        title: 'Success',
                        text: 'Record saved successfully.',
                        icon: 'success'
                    }).then((result) => {
                        document.location = '@Url.Action("DriverRegistration", "Driver")';
                    });
                } else {
                    Swal.fire({
                        title: 'Error',
                        text: response.Message,
                        icon: 'error'
                    })
                }
            },
            error: function (err) {
                alert(err.responseText);
            }
        });
    }

    function Load() {
        $.ajax({
            url: "/Driver/GetDrivers",
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                $('#tblSummary').DataTable({
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": response,
                    "bPaginate": true,
                    "pageLength": 25,
                    "bInfo": true,
                    "paging": true,
                    order: [],
                    "searching": true,
                    "columns": [
                        { "data": "DriverName" },
                        { "data": "DOB" },
                        { "data": "LicenseNo" },
                        { "data": "MobileNo" }
                    ],
                    mark: true
                });
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
    }

    function ShowSummary() {
        $("#DriverEntry").hide();
        $("#DriverSummary").show();
    }

    function ShowEntry() {
        $("#DriverSummary").hide();
        $("#DriverEntry").show();
    }
</script>