Controllers/Bidding/BiddingController.cs
using FutureTransport.Filters;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BE = FutureTransportEntities.BusinessEntities;
using BL = FutureTransportBuisenessLayer.Bidding;

namespace FutureTransport.Controllers.Bidding
{
    [UserAuthenticationFilter]
    public class BiddingController : Controller
    {
        BL.BiddingDataProvider DataProvider = new BL.BiddingDataProvider();

        public ActionResult Bidding()
        {
            int BookingId = 0;
            string BookingNo = "0";
            int VendorId = Convert.ToInt16(Session["UserId"]);

            BE.Bookings data = new BE.Bookings();
            if (BookingId != 0 && BookingNo != "0")
            {
                ViewBag.BookingId = BookingId;
                ViewBag.BookingNo = BookingNo;
            }
            else
            {
                ViewBag.BookingId = 0;
                ViewBag.BookingNo = "0";
            }
            ViewBag.VendorId = VendorId;
            return View();
        }

        public JsonResult GetBiddings(BE.Bookings BD)
        {
            int VendorId = Convert.ToInt16(Session["UserId"]);
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBiddings(BD, VendorId);
            return Json(list);
        }

        public JsonResult AjaxAcceptedBidding(BE.Bookings SD)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            message = DataProvider.AcceptedBidding(SD);
            return Json(message);
        }

        public ActionResult LiveBids()
        {
            int BookingId = 0;
            string BookingNo = "0";

            BE.Bookings data = new BE.Bookings();
            if (BookingId != 0 && BookingNo != "0")
            {
                ViewBag.BookingId = BookingId;
                ViewBag.BookingNo = BookingNo;
            }
            else
            {
                ViewBag.BookingId = 0;
                ViewBag.BookingNo = "0";
            }
            return View();
        }

        public JsonResult GetLiveBiddings(BE.Bookings GD)
        {
            int VendorId = Convert.ToInt16(Session["UserId"]);
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetLiveBiddings(GD, VendorId);
            return Json(list);
        }

        public ActionResult PendingMovements()
        {
            return View();
        }

        public JsonResult GetPendingMovements(BE.Bookings GD)
        {
            int VendorId = Convert.ToInt16(Session["UserId"]);
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetPendingMovements(GD, VendorId);
            return Json(list);
        }

        public ActionResult BookingDetails(string BookingNo)
        {
            List<BE.Drivers> drivers = DataProvider.GetDrivers();
            ViewBag.DriverDropdown = new SelectList(drivers, "DriverId", "DriverName");
            List<BE.Vehicles> vehicles = DataProvider.GetVehicles();
            ViewBag.VehicleDropdown = new SelectList(vehicles, "VehicleId", "VehicleNumber");
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        public JsonResult GetBookingDetails(string BN)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingDetails(BN);
            return Json(list);
        }

        public JsonResult AjaxAddDriver(BE.Bookings SD)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            message = DataProvider.UpdateAddDriver(SD);
            return Json(message);
        }

        public JsonResult AjaxAddVehicle(BE.Bookings SV)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            message = DataProvider.UpdateAddVehicle(SV);
            return Json(message);
        }

        public ActionResult BookingHistory()
        {
            return View();
        }

        public JsonResult GetBookingsHistory(BE.Bookings GDH)
        {
            int VendorId = Convert.ToInt16(Session["UserId"]);
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingsHistory(GDH, VendorId);
            return Json(list);
        }

        public ActionResult BookingDocuments()
        {
            return View();
        }

        public JsonResult GetBookingDocuments(BE.Bookings GDL)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingDocuments(GDL);
            return Json(list);
        }

        public ActionResult LiveTrips()
        {
            return View();
        }

        public JsonResult GetBookingsLiveTrips()
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingsLiveTrips();
            return Json(list);
        }

        public ActionResult LiveTripsDetails(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        public JsonResult GetLiveTripsDetails(string BN)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetLiveTripsDetails(BN);
            return Json(list);
        }

        public JsonResult GetUpdateDate(string BN, string SN)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetUpdateDate(BN, SN);
            return Json(list);
        }

        public JsonResult AjaxUpdateDropOffBooking(BE.Bookings UDD)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            message = DataProvider.UpdateDropOffBooking(UDD);
            return Json(message);
        }

        public ActionResult TripsCompleted()
        {
            return View();
        }

        public JsonResult GetBookingsTripsCompleted(BE.Bookings GDC)
        {
            int VendorId = Convert.ToInt16(Session["UserId"]);
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingsTripsCompleted(GDC, VendorId);
            return Json(list);
        }

        public ActionResult TripsCompletedDetails(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        public JsonResult GetTripsCompletedDetails(string BN)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetTripsCompletedDetails(BN);
            return Json(list);
        }

        public ActionResult Documents(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        [HttpPost]
        public ActionResult ShowDeliveryAttachment(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        [HttpPost]
        public ActionResult StoreDeliveryAttachment(string DocName, string FilePath, string ContentType)
        {
            TempData["DocName"] = DocName;
            TempData["FilePath"] = FilePath;
            TempData["ContentType"] = ContentType;
            int i = 1;
            return Json(i);
        }

        public FileResult DownloadDeliveryAttachment(int id)
        {
            string DocName = Convert.ToString(TempData["DocName"]);
            string FilePath = Convert.ToString(TempData["FilePath"]);
            string ContentType = Convert.ToString(TempData["ContentType"]);
            byte[] fileBytes = System.IO.File.ReadAllBytes(FilePath);
            return File(fileBytes, ContentType, DocName);
        }

        public JsonResult GetDeliveryAttachment(string DD)
        {
            List<BE.Documents> list = new List<BE.Documents>();
            list = DataProvider.GetDeliveryAttachment(DD);
            return Json(list);
        }

        public ActionResult LorryAttachment()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AjaxUploadLorryAttachment(BE.Documents fileData)
        {
            BE.Documents documents = new BE.Documents();
            if (Request.Files.Count > 0)
            {
                try
                {
                    int Userid = Convert.ToInt16(Session["UserId"]);
                    string Type = fileData.EnqType;
                    Type = Type + Userid;
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        string fname;
                        string root = Server.MapPath("~/Uploads/Lorry/" + Type + "/");
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }
                        string contentType;
                        contentType = MimeMapping.GetMimeMapping(fname);

                        if (!Directory.Exists(root))
                        {
                            Directory.CreateDirectory(root);
                        }
                        string check = Path.Combine(Server.MapPath("~/Uploads/Lorry/" + Type + "/"), fname);
                        if (System.IO.File.Exists(fname))
                        {
                            System.IO.File.Delete(fname);
                        }
                        file.SaveAs(check);

Views/Bidding/AdditionalAttachment.cshtml
<div>
    <div class="modal-header">
        <h5 class="modal-title">Document</h5>
        <label id="MSNoFile" style="visibility:hidden"></label>
        <button type="button" class="close" id="isClosed" onclick="isClosed()">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form>
            <div class="form-group">
                <input type="file" id="documentAttachment" name="postedFile" />
                <input type="Button" class="btn btn-primary" id="btnUpload" value="Upload" />
            </div>
            <div class="form-group">
                <div class="table-responsive">
                    <table id="documentAttachmentTable" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="wd-15p sorting">Document Name</th>
                                <th style="width:15px"></th>
                                <th style="width:15px"></th>
                            </tr>
                        </thead>
                        <tbody style="box-sizing :border-box;"></tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <label hidden id="load"></label>
        <button class="btn btn-info pull-right" id="btnDone">Done</button>
    </div>
</div>

@using (Html.BeginForm("DownloadAdditionalAttachment", "Bidding", FormMethod.Post))
{
    <input type="hidden" id="hiddenFile" name="id" />
    <button type="submit" class="btn btn-primary" id="btnDownload" style="display:none">Download</button>
}

<script>
    var type = 'VendorDocument';
    var table = [];

    $(document).ready(function () {
        $('#documentAttachmentTable').dataTable({
            "bLengthChange": false,
            "bInfo": false,
            "bPaginate": false,
            "bFilter": false,
            "paging": false
        });

        table = additionalAttachment;

        if (table.length != 0) {
            $('#documentAttachmentTable').dataTable({
                "bLengthChange": false,
                "bInfo": false,
                "bPaginate": false,
                "bFilter": false,
                "paging": false,
                "destroy": true,
                "bLengthChange": false,
                "aaData": table,
                "columns": [
                    { "data": "DocName" },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningId + ')"><i class="fa fa-download"></i></a>';
                            }
                            return data;
                        }
                    },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningId + ')"><i class="fa fa-trash-o"></i></a>';
                            }
                            return data;
                        }
                    }
                ]
            });
            countRows();
        }
    });

    $(document).ready(function () {
        $('#btnUpload').click(function () {
            var MSNoFile1 = "";

            if (window.FormData !== undefined) {

                var fileUpload = $("#documentAttachment").get(0);
                var files = fileUpload.files;
                var fileData = new FormData();

                if (files.length == 0) {
                    alert("Please select a file!")
                    return false;
                }
                else {
                    addAttachment(type);
                }
            }
            else {
                alert("FormData is not supported");
            }
        });
    });

    function addAttachment(data) {
        var fileUpload = $("#documentAttachment").get(0);
        var files = fileUpload.files;
        var fileData = new FormData();
        var UploadType = data;

        var iSize = document.getElementById('documentAttachment').files[0].size / 1024
        iSize = (Math.round((iSize / 1024) * 100) / 100)

        if (iSize > 25) {
            alert("Selected file size more than 25 MB");
            return false;
        }

        for (var i = 0; i < files.length; i++) {
            fileData.append(files[i].name, files[i]);
        }
        fileData.append('EnqType', UploadType);
        runningNo++;

        $.ajax({
            url: '/Bidding/AjaxUploadAdditionalAttachment',
            type: "POST",
            contentType: false,
            processData: false,
            data: fileData,
            success: function (Data) {
                var element = {};
                element.DocName = Data.DocName;
                element.RunningId = runningNo;
                element.FilePath = Data.FilePath;
                element.ContentType = Data.ContentType;
                element.UploadType = type;
                additionalAttachment.push(element);
                table = additionalAttachment;

                $('#documentAttachmentTable').dataTable({
                    "bLengthChange": false,
                    "bInfo": false,
                    "bPaginate": false,
                    "bFilter": false,
                    "paging": false,
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": table,
                    "columns": [
                        { "data": "DocName" },
                        {
                            "data": "FilePath",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningId + ')"><i class="fa fa-download"></i></a>';
                                }
                                return data;
                            }
                        },
                        {
                            "data": "ContentType",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningId + ')"><i class="fa fa-trash-o"></i></a>';
                                }
                                return data;
                            }
                        }
                    ]
                });
                countRows();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
        $("#documentAttachment").val('');
    }

    function downloadAttachment(runningNo) {
        var no = runningNo;
        var DocName, FilePath, ContentType;
        for (i = 0; i < table.length; i++) {
            if (table[i].RunningId == no) {
                DocName = table[i].DocName;
                FilePath = table[i].FilePath;
                ContentType = table[i].ContentType;
            }
        }
        var id = 0;
        var data = { 'DocName': DocName, 'FilePath': FilePath, 'ContentType': ContentType }
        data = JSON.stringify(data);

        $.ajax({
            url: '/Bidding/StoreAdditionalAttachment',
            type: "POST",
            contentType: "application/json; charset=utf-8",
            data: data,
            success: function (Data) {
                id = Data;
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
        $("#hiddenFile").val(id);
        $("#btnDownload")[0].click();
    }

    function deleteAttachment(id) {
        var r = confirm("Are you sure want to delete this file!");
        if (r == true) {
            var no = id;
            for (i = 0; i < table.length; i++) {
                if (table[i].RunningId == no) {
                    table.splice(i, 1);
                }
            }
            $('#documentAttachmentTable').dataTable({
                "bLengthChange": false,
                "bInfo": false,
                "bPaginate": false,
                "bFilter": false,
                "paging": false,
                "destroy": true,
                "bLengthChange": false,
                "aaData": table,
                "columns": [
                    { "data": "DocName" },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningId + ')"><i class="fa fa-download"></i></a>';
                            }
                            return data;
                        }
                    },
                    {
                        "data": "ContentType",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningId + ')"><i class="fa fa-trash-o"></i></a>';
                            }
                            return data;
                        }
                    }
                ]
            });
            countRows();
        }
    }

    function countRows() {
        var table = $('#documentAttachmentTable').DataTable();
        var RowCount = table.rows().count();
    }

    $('#btnDone').click(function () {
        totalAttchment = additionalAttachment;
        for (i = 0; i < totalAttchment.length; i++) {
            var element = {};
            element.UploadFor = "Vendor Document";
            element.DocName = totalAttchment[i].DocName;
            element.FilePath = totalAttchment[i].FilePath;
            element.ContentType = totalAttchment[i].ContentType;
            masterAttachment.push(element);
        }

        var data = { 'BN': BookingNo, 'A': masterAttachment };
        data = JSON.stringify(data);
        debugger;
        $.ajax({
            type: 'post',
            url: '/Bidding/AjaxAdditionalAttachment',
            data: data,
            async: false,
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                if (response.Status != 0) {
                    Swal.fire({
                        title: 'Success',
                        text: response.Message,
                        icon: 'success'
                    }).then((result) => {
                        $('#attachmentModal').modal('hide');
                    });
                } else {
                    alert("Please select a file!");
                }
            },
            error: function (err) {
                alert(err.responseText);
            }
        });
        $("#load").load("/Bidding/Documents?BookingNo=" + BookingNo);
    });

    function isClosed() {
        $('#attachmentModal').modal('hide');
        $("#load").load("/Bidding/Documents?BookingNo=" + BookingNo);
    }
</script>

Views/Bidding/Documents.cshtml
<div class="page-header">
    <h4 class="page-title">Documents</h4>
    <ol class="breadcrumb" id="IsDirect">
        <li class="breadcrumb-item">
            <a onclick="GetBack()" class="btn btn-primary btn-primary text-right" style="align-content:center;color:white" title="Back" data-toggle="tooltip" data-placement="bottom">
                <i class="fa fa-arrow-left"></i>
            </a>
        </li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="mt-5">
            <div class="table-responsive">
                <table class="table table-bordered text-center table-hover w-100 card-table m-0 text-nowrap" id="tblDocuments">
                    <thead class="bg-primary">
                        <tr>
                            <th>SrNo</th>
                            <th>Document</th>
                            <th>View</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>E- Delivery Order</td>
                            <td><button class="btn btn-primary" title="View" data-toggle="tooltip" data-placement="bottom" onclick="showDeliveryAttachment()"><i class="fa fa-eye"></i></button></td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>E- Lorry Receipt</td>
                            <td><button class="btn btn-blue" title="Upload" data-toggle="tooltip" data-placement="bottom" onclick="addLorryAttachment()"><i class="fa fa-upload"></i></button></td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Empty Offloading Receipt</td>
                            <td><button class="btn btn-blue" title="Upload" data-toggle="tooltip" data-placement="bottom" onclick="addOffloadingAttachment()"><i class="fa fa-upload"></i></button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="float-right m-5">
                <button class="btn btn-success mr-5" title="Additional Documents" data-toggle="tooltip" data-placement="bottom" onclick="addAdditionalAttachment()">Additional Documents</button>
            </div>
        </div>

        <div class="modal fade" id="attachmentModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content" id='attachmentModalContent'></div>
            </div>
        </div>
    </div>
</div>

<script>
    var DocId = 0;
    var BookingId = 0;
    var BookingNo = "@ViewBag.BookingNo";

    var runningNo = 1;

    var lorryAttachment = [];
    var lorryAttachment;
    var totalLorryAttchment = [];
    var masterLorryAttachment = [];

    var offloadingAttachment = [];
    var offloadingAttachment;
    var totalOffloadingAttachment = [];
    var masterOffloadingAttachment = [];

    var additionalAttachment = [];
    var additionalAttachment;
    var totalAttchment = [];
    var masterAttachment = [];

    function GetBack() {
        document.location = '@Url.Action("BookingDocuments", "Bidding")';
    }

    function showDeliveryAttachment() {
        var data = { 'BookingNo': BookingNo };
        data = JSON.stringify(data);

        $.ajax({
            type: "POST",
            url: "/Bidding/ShowDeliveryAttachment",
            data: data,
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                $('#attachmentModalContent').html(response);
                $('#attachmentModal').modal('show');
            },
            failure: function (response) {
                alert(response);
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        })
    }

    function addLorryAttachment() {
        $.ajax({
            type: "POST",
            url: "/Bidding/LorryAttachment",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                $('#attachmentModalContent').html(response);
                $('#attachmentModal').modal('show');
            },
            failure: function (response) {
                alert(response);
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        })
    }

    function addOffloadingAttachment() {
        $.ajax({
            type: "POST",
            url: "/Bidding/OffloadingAttachment",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                $('#attachmentModalContent').html(response);
                $('#attachmentModal').modal('show');
            },
            failure: function (response) {
                alert(response);
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        })
    }

    function addAdditionalAttachment() {
        $.ajax({
            type: "POST",
            url: "/Bidding/AdditionalAttachment",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                $('#attachmentModalContent').html(response);
                $('#attachmentModal').modal('show');
            },
            failure: function (response) {
                alert(response);
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        })
    }
</script>

Views/Bidding/TripsCompletedDetails.cshtml
<div class="page-header">
    <h4 class="page-title">Booking Details</h4>
    <ol class="breadcrumb" id="IsDirect">
        <li class="breadcrumb-item">
            <a onclick="GetBack()" class="btn btn-primary btn-primary text-right" style="align-content:center;color:white">
                <i class="fa fa-arrow-left" data-placement="bottom" title="Back"></i>
            </a>
        </li>
    </ol>
</div>
<div class="card">
    <div class="card-body">
        <div class="row mt-5">
            <div class="col-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-4">
                            <label class="form-label mt-1">Booking No :</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            @Html.TextBox("BookingNo", null, new { @class = "form-control", @id = "BookingNo", name = "BookingNo", @Value = @ViewBag.BookingNo, @readonly = "readonly" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="th_Background table table-striped table-bordered text-center text-nowrap" style="width:100%" id="tblDetailsSummary">
                <thead class="bg-primary">
                    <tr>
                        <th>Container Size</th>
                        <th>Container Type</th>
                        <th>Weight</th>
                        <th>Container No</th>
                        <th>Pickup Date</th>
                        <th>Dropoff Date</th>
                        <th>Driver</th>
                        <th>Vehicle</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        LoadDetails();
    });

    function GetBack() {
        document.location = '@Url.Action("TripsCompleted", "Bidding")';
    }

    function LoadDetails() {
        var BN = document.getElementById("BookingNo").value;

        var data = { 'BN': BN }
        data = JSON.stringify(data);

        $.ajax({
            url: "/Bidding/GetTripsCompletedDetails",
            data: data,
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                $('#tblDetailsSummary').DataTable({
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": response,
                    "bPaginate": true,
                    "pageLength": 25,
                    "bInfo": true,
                    "paging": true,
                    order: [],
                    "searching": true,
                    "columns": [
                        { "data": "ContainerSize" },
                        { "data": "ContainerType" },
                        { "data": "Weight" },
                        { "data": "ContainerNo" },
                        { "data": "PickUpDate" },
                        { "data": "DropOffDate" },
                        { "data": "Driver" },
                        { "data": "Vehicle" }
                    ],
                    mark: true
                });
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
    }
</script>