Controllers/Booking/BookingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL = FutureTransportBuisenessLayer.Booking;
using BE = FutureTransportEntities.BusinessEntities;
using FutureTransport.Filters;
using HL = FutureTransportDataLayer.Helper;
using QRCoder;
using System.Drawing;

namespace FutureTransport.Controllers.Booking
{
    [UserAuthenticationFilter]
    public class BookingController : Controller
    {
        BL.BookingDataProvider DataProvider = new BL.BookingDataProvider();
        HL.DBOperationsForCustomerPortal DBHelper = new HL.DBOperationsForCustomerPortal();

        public ActionResult LiveBookings()
        {
            int BookingId = 0;
            string BookingNo = "0";
            int UserId = Convert.ToInt16(Session["UserId"]);

            List<BE.ContainerTypes> containerTypes = DataProvider.GetContainerTypes();
            ViewBag.CTDropdown = new SelectList(containerTypes, "ContainerTypeID", "ContainerType");
            BE.Bookings data = new BE.Bookings();
            if (BookingId != 0 && BookingNo != "0")
            {
                ViewBag.BookingId = BookingId;
                ViewBag.BookingNo = BookingNo;
            }
            else
            {
                ViewBag.BookingId = 0;
                ViewBag.BookingNo = "0";
            }
            ViewBag.UserId = UserId;
            return View();
        }

        public JsonResult GetBookings(string ShipmentType)
        {
            int UserId = Convert.ToInt16(Session["UserId"]);
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookings(ShipmentType, UserId);
            return Json(list);
        }

        public JsonResult AjaxAddBooking(List<BE.Bookings> BD)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            if (BD != null)
            {
                DataTable dataTable = new DataTable();
                dataTable.Columns.Add("BookingId");
                dataTable.Columns.Add("BookingNo");
                dataTable.Columns.Add("UserId");
                dataTable.Columns.Add("ShipmentType");
                dataTable.Columns.Add("PlanDate");
                dataTable.Columns.Add("PickUpLocation");
                dataTable.Columns.Add("DropOffLocation");
                dataTable.Columns.Add("ContainerSizeTwenty");
                dataTable.Columns.Add("ContainerTypeTwenty");
                dataTable.Columns.Add("WeightTwenty");
                dataTable.Columns.Add("WeightTwentyUnit");
                dataTable.Columns.Add("QuantityTwenty");
                dataTable.Columns.Add("ContainerSizeFourty");
                dataTable.Columns.Add("ContainerTypeFourty");
                dataTable.Columns.Add("WeightFourty");
                dataTable.Columns.Add("WeightFourtyUnit");
                dataTable.Columns.Add("QuantityFourty");
                dataTable.Columns.Add("ContainerSizeFourtyFive");
                dataTable.Columns.Add("ContainerTypeFourtyFive");
                dataTable.Columns.Add("WeightFourtyFive");
                dataTable.Columns.Add("WeightFourtyFiveUnit");
                dataTable.Columns.Add("QuantityFourtyFive");
                dataTable.TableName = "PT_AddBooking";
                foreach (BE.Bookings item in BD)
                {
                    DataRow row = dataTable.NewRow();
                    row["BookingId"] = item.BookingId;
                    row["BookingNo"] = item.BookingNo;
                    row["UserId"] = item.UserId;
                    row["ShipmentType"] = item.ShipmentType;
                    row["PlanDate"] = item.PlanDate;
                    row["PickUpLocation"] = item.PickUpLocation;
                    row["DropOffLocation"] = item.DropOffLocation;
                    row["ContainerSizeTwenty"] = item.ContainerSizeTwenty;
                    row["ContainerTypeTwenty"] = item.ContainerTypeTwenty;
                    row["WeightTwenty"] = item.WeightTwenty;
                    row["WeightTwentyUnit"] = item.WeightTwentyUnit;
                    row["QuantityTwenty"] = item.QuantityTwenty;
                    row["ContainerSizeFourty"] = item.ContainerSizeFourty;
                    row["ContainerTypeFourty"] = item.ContainerTypeFourty;
                    row["WeightFourty"] = item.WeightFourty;
                    row["WeightFourtyUnit"] = item.WeightFourtyUnit;
                    row["QuantityFourty"] = item.QuantityFourty;
                    row["ContainerSizeFourtyFive"] = item.ContainerSizeFourtyFive;
                    row["ContainerTypeFourtyFive"] = item.ContainerTypeFourtyFive;
                    row["WeightFourtyFive"] = item.WeightFourtyFive;
                    row["WeightFourtyFiveUnit"] = item.WeightFourtyFiveUnit;
                    row["QuantityFourtyFive"] = item.QuantityFourtyFive;
                    dataTable.Rows.Add(row);
                }
                message = DataProvider.AddBooking(dataTable);
            }
            return Json(message);
        }

        public ActionResult BookingDetails(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        public JsonResult AjaxDeleteBooking(string DD)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            message = DataProvider.DeleteBooking(DD);
            return Json(message);
        }

        public JsonResult AjaxAcceptedBooking(string AD, string EI)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            string email = "";
            message = DataProvider.AcceptedBooking(AD);
            email = DataProvider.SendEmailAcceptedBooking(EI);
            return Json(message);
        }

        public JsonResult AjaxRejectedBooking(string RD)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            message = DataProvider.RejectedBooking(RD);
            return Json(message);
        }

        public JsonResult GetBookingDetails(string BN)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingDetails(BN);
            return Json(list);
        }

        public JsonResult AjaxAddBookingDetails(List<BE.Bookings> CN)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            if (CN != null)
            {
                DataTable dataTable = new DataTable();
                dataTable.Columns.Add("BookingNo");
                dataTable.Columns.Add("SizeNo");
                dataTable.Columns.Add("ContainerNo");
                dataTable.Columns.Add("PickUpDate");
                dataTable.TableName = "PT_AddBookingDetails";
                foreach (BE.Bookings item in CN)
                {
                    DataRow row = dataTable.NewRow();
                    row["BookingNo"] = item.BookingNo;
                    row["SizeNo"] = item.SizeNo;
                    row["ContainerNo"] = item.ContainerNo;
                    row["PickUpDate"] = item.PickUpDate;
                    dataTable.Rows.Add(row);
                }
                message = DataProvider.AddBookingDetails(dataTable);
            }
            return Json(message);
        }

        public JsonResult AjaxUpdatePickUpBooking(BE.Bookings UPD)
        {
            BE.ResponseMessage message = new BE.ResponseMessage();
            message = DataProvider.UpdatePickUpBooking(UPD);
            return Json(message);
        }

        public ActionResult PendingMovements()
        {
            return View();
        }

        public JsonResult GetPendingMovements(BE.Bookings GD)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetPendingMovements(GD);
            return Json(list);
        }

        public ActionResult BookingHistory()
        {
            return View();
        }

        public JsonResult GetBookingsHistory(string ShipmentType)
        {
            int UserId = Convert.ToInt16(Session["UserId"]);
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingsHistory(ShipmentType, UserId);
            return Json(list);
        }

        public ActionResult LiveTrips()
        {
            return View();
        }

        public JsonResult GetBookingsLiveTrips()
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingsLiveTrips();
            return Json(list);
        }

        public ActionResult LiveTripsDetails(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        public JsonResult GetLiveTripsDetails(string BN)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetLiveTripsDetails(BN);
            return Json(list);
        }

        [HttpPost]
        public ActionResult ShowDocuments(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        [HttpPost]
        public ActionResult StoreDocuments(string DocNameA, string FilepathA, string ContentTypeA)
        {
            TempData["DocName"] = DocNameA;
            TempData["FilePath"] = FilepathA;
            TempData["ContentType"] = ContentTypeA;
            int i = 1;
            return Json(i);
        }

        public FileResult DownloadDocuments(int id)
        {
            string DocName = Convert.ToString(TempData["DocName"]);
            string Filepath = Convert.ToString(TempData["FilePath"]);
            string ContentType = Convert.ToString(TempData["ContentType"]);
            byte[] fileBytes = System.IO.File.ReadAllBytes(Filepath);
            return File(fileBytes, ContentType, DocName);
        }

Views/Booking/BookingDetails.cshtml
<div id="refresh">
    <div class="page-header">
        <h4 class="page-title">Booking Details</h4>
        <ol class="breadcrumb" id="IsDirect">
            <li class="breadcrumb-item">
                <a onclick="GetBack()" class="btn btn-primary btn-primary text-right" style="align-content:center;color:white" title="Back" data-toggle="tooltip" data-placement="bottom">
                    <i class="fa fa-arrow-left"></i>
                </a>
            </li>
        </ol>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row mt-5">
                <div class="col-6">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-4">
                                <label class="form-label mt-1">Booking No :</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-4">
                                @Html.TextBox("BookingNo", null, new { @class = "form-control", @id = "BookingNo", name = "BookingNo", @Value = @ViewBag.BookingNo, @readonly = "readonly" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table class="th_Background table table-striped table-bordered text-center text-nowrap" style="width:100%" id="tblDetailsSummary">
                    <thead class="bg-primary">
                        <tr>
                            <th>Container Size</th>
                            <th>Container Type</th>
                            <th>Weight</th>
                            <th>Container No</th>
                            <th>Pickup Date</th>
                            <th>Driver</th>
                            <th>Vehicle</th>
                        </tr>
                    </thead>
                </table>
            </div>

            <div class="row">
                <div class="col-sm-12 col-md-4">
                    <button class="target btn btn-success" title="Save" data-toggle="tooltip" data-placement="bottom" onclick="SaveDetails()"><i class="fa fa-save"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var ContainerM = [];
    var BookingNo = "";

    $(document).ready(function () {
        BookingNo = "@ViewBag.BookingNo";
        LoadDetails();
    });

    function GetBack() {
        document.location = '@Url.Action("PendingMovements", "Booking")';
    }

    function LoadDetails() {
        var BN = document.getElementById("BookingNo").value;

        var data = { 'BN': BN }
        data = JSON.stringify(data);

        $.ajax({
            url: "/Booking/GetBookingDetails",
            data: data,
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                ContainerM = response;
                $('#tblDetailsSummary').DataTable({
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": response,
                    "bPaginate": true,
                    "pageLength": 25,
                    "bInfo": true,
                    "paging": true,
                    order: [],
                    "searching": true,
                    "columns": [
                        { "data": "ContainerSize" },
                        { "data": "ContainerType" },
                        { "data": "Weight" },
                        {
                            "data": "ContainerNo",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.ContainerNo == "") {
                                        data = "<div class=\"text-center\"><input type=\"text\" class=\"from-control\" id=\"ContainerNo" + row.SizeNo + "\" onchange=\"GetData('" + row.SizeNo + "')\" size=\"30\"/></div>"
                                    }
                                    else {
                                        data = row.ContainerNo
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "PickUpDate",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.PickUpDate == "") {
                                        data = "<div class=\"text-center\"><input type=\"text\" class=\"from-control datePicker\" id=\"PickUpDate" + row.SizeNo + "\" onchange=\"GetData('" + row.SizeNo + "')\" size=\"20\"/></div>"
                                    }
                                    else {
                                        data = row.PickUpDate
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "Driver",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.Driver == "") {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.Driver
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "Vehicle",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.Vehicle == "") {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.Vehicle
                                    }
                                }
                                return data;
                            }
                        }
                    ],
                    mark: true
                });
                $(".datePicker").datepicker({
                    autoclose: true,
                    todayHighlight: true,
                    format: 'dd M yyyy',
                    language: "tr",
                    changeMonth: true,
                    changeYear: true,
                });
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
    }

    function GetData(SizeNo) {
        for (var i = 0; i < ContainerM.length; i++) {
            if (SizeNo == ContainerM[i].SizeNo) {
                ContainerM[i].ContainerNo = $("#ContainerNo" + SizeNo).val();
                ContainerM[i].PickUpDate = $("#PickUpDate" + SizeNo).val();
            }
        }
    }

    function SaveDetails() {
        var TotalContainerSize = [];
        for (var i = 0; i < ContainerM.length; i++) {
            var element = {};
            element.BookingNo = ContainerM[i].BookingNo;
            element.SizeNo = ContainerM[i].SizeNo;
            element.ContainerNo = ContainerM[i].ContainerNo;
            element.PickUpDate = ContainerM[i].PickUpDate;
            TotalContainerSize.push(element);
        }

        var data = { 'CN': TotalContainerSize };
        data = JSON.stringify(data);

        $.ajax({
            type: 'post',
            url: '/Booking/AjaxAddBookingDetails',
            data: data,
            async: false,
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                if (response.Status != 0) {
                    Swal.fire({
                        title: 'Success',
                        text: response.Message,
                        icon: 'success'
                    }).then((result) => {
                        $('#refresh').load("/Booking/BookingDetails?BookingNo=" + BookingNo);
                    });
                } else {
                    Swal.fire({
                        title: 'Error',
                        text: response.Message,
                        icon: 'error'
                    })
                }
            },
            error: function (err) {
                alert(err.responseText);
            }
        });
    }
</script>

Views/Booking/DeliveryAttachment.cshtml
<div>
    <div class="modal-header">
        <h5 class="modal-title">Delivery Document</h5>
        <label id="MSNoFile" style="visibility:hidden"></label>
        <button type="button" class="close" id="isClosed" onclick="isClosed()">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <form>
            <div class="form-group">
                <input type="file" id="documentAttachment" name="postedFile" />
                <input type="Button" class="btn btn-primary" id="btnUpload" value="Upload" />
            </div>
            <div class="form-group">
                <div class="table-responsive">
                    <table id="documentAttachmentTable" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th class="wd-15p sorting">Delivery Document Name</th>
                                <th style="width:15px"></th>
                                <th style="width:15px"></th>
                            </tr>
                        </thead>
                        <tbody style="box-sizing :border-box;"></tbody>
                    </table>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <label hidden id="load"></label>
        <button class="btn btn-info pull-right" id="btnDone">Done</button>
    </div>
</div>

@using (Html.BeginForm("DownloadDeliveryAttachment", "Booking", FormMethod.Post))
{
    <input type="hidden" id="hiddenFile" name="id" />
    <button type="submit" class="btn btn-primary" id="btnDownload" style="display:none">Download</button>
}

<script>
    var type = 'DeliveryDocument';
    var table = [];

    $(document).ready(function () {
        $('#documentAttachmentTable').dataTable({
            "bLengthChange": false,
            "bInfo": false,
            "bPaginate": false,
            "bFilter": false,
            "paging": false
        });

        table = deliveryAttachment;

        if (table.length != 0) {
            $('#documentAttachmentTable').dataTable({
                "bLengthChange": false,
                "bInfo": false,
                "bPaginate": false,
                "bFilter": false,
                "paging": false,
                "destroy": true,
                "bLengthChange": false,
                "aaData": table,
                "columns": [
                    { "data": "DocName" },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningId + ')"><i class="fa fa-download"></i></a>';
                            }
                            return data;
                        }
                    },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningId + ')"><i class="fa fa-trash-o"></i></a>';
                            }
                            return data;
                        }
                    }
                ]
            });
            countRows();
        }
    });

    $(document).ready(function () {
        $('#btnUpload').click(function () {
            var MSNoFile1 = "";

            if (window.FormData !== undefined) {

                var fileUpload = $("#documentAttachment").get(0);
                var files = fileUpload.files;
                var fileData = new FormData();

                if (files.length == 0) {
                    alert("Please select a file!")
                    return false;
                }
                else {
                    addAttachment(type);
                }
            }
            else {
                alert("FormData is not supported");
            }
        });
    });

    function addAttachment(data) {
        var fileUpload = $("#documentAttachment").get(0);
        var files = fileUpload.files;
        var fileData = new FormData();
        var UploadType = data;

        var iSize = document.getElementById('documentAttachment').files[0].size / 1024
        iSize = (Math.round((iSize / 1024) * 100) / 100)

        if (iSize > 25) {
            alert("Selected file size more than 25 MB!");
            return false;
        }

        for (var i = 0; i < files.length; i++) {
            fileData.append(files[i].name, files[i]);
        }
        fileData.append('EnqTypeA', UploadType);
        runningNo++;

        $.ajax({
            url: '/Booking/AjaxUploadDeliveryAttachment',
            type: "POST",
            contentType: false,
            processData: false,
            data: fileData,
            success: function (Data) {
                var element = {};
                element.DocName = Data.DocName;
                element.RunningId = runningNo;
                element.FilePath = Data.FilePath;
                element.ContentType = Data.ContentType;
                element.UploadType = type;
                deliveryAttachment.push(element);
                table = deliveryAttachment;

                $('#documentAttachmentTable').dataTable({
                    "bLengthChange": false,
                    "bInfo": false,
                    "bPaginate": false,
                    "bFilter": false,
                    "paging": false,
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": table,
                    "columns": [
                        { "data": "DocName" },
                        {
                            "data": "FilePath",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningId + ')"><i class="fa fa-download"></i></a>';
                                }
                                return data;
                            }
                        },
                        {
                            "data": "ContentType",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningId + ')"><i class="fa fa-trash-o"></i></a>';
                                }
                                return data;
                            }
                        }
                    ]
                });
                countRows();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
        $("#documentAttachment").val('');
    }

    function downloadAttachment(runningNo) {
        var no = runningNo;
        var DocName, FilePath, ContentType;
        for (i = 0; i < table.length; i++) {
            if (table[i].RunningId == no) {
                DocName = table[i].DocName;
                FilePath = table[i].FilePath;
                ContentType = table[i].ContentType;
            }
        }
        var id = 0;
        var data = { 'DocName': DocName, 'FilePath': FilePath, 'ContentType': ContentType }
        data = JSON.stringify(data);

        $.ajax({
            url: '/Booking/StoreDeliveryAttachment',
            type: "POST",
            contentType: "application/json; charset=utf-8",
            data: data,
            success: function (Data) {
                id = Data;
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
        $("#hiddenFile").val(id);
        $("#btnDownload")[0].click();
    }

    function deleteAttachment(id) {
        var r = confirm("Are you sure want to delete this file!");
        if (r == true) {
            var no = id;
            for (i = 0; i < table.length; i++) {
                if (table[i].RunningId == no) {
                    table.splice(i, 1);
                }
            }
            $('#documentAttachmentTable').dataTable({
                "bLengthChange": false,
                "bInfo": false,
                "bPaginate": false,
                "bFilter": false,
                "paging": false,
                "destroy": true,
                "bLengthChange": false,
                "aaData": table,
                "columns": [
                    { "data": "DocName" },
                    {
                        "data": "FilePath",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-primary" onclick="downloadAttachment(' + row.RunningId + ')"><i class="fa fa-download"></i></a>';
                            }
                            return data;
                        }
                    },
                    {
                        "data": "ContentType",
                        "render": function (data, type, row, meta) {
                            if (type === 'display') {
                                data = '<a class="btn btn-danger" onclick="deleteAttachment(' + row.RunningId + ')"><i class="fa fa-trash-o"></i></a>';
                            }
                            return data;
                        }
                    }
                ]
            });
            countRows();
        }
    }

    function countRows() {
        var table = $('#documentAttachmentTable').DataTable();
        var RowCount = table.rows().count();
    }

    $('#btnDone').click(function () {
        totalDeliveryAttchment = deliveryAttachment;
        for (i = 0; i < totalDeliveryAttchment.length; i++) {
            var element = {};
            element.UploadFor = "Vendor Document";
            element.DocName = totalDeliveryAttchment[i].DocName;
            element.FilePath = totalDeliveryAttchment[i].FilePath;
            element.ContentType = totalDeliveryAttchment[i].ContentType;
            masterDeliveryAttachment.push(element);
        }

        var data = { 'BN': BookingNo, 'A': masterDeliveryAttachment };
        data = JSON.stringify(data);

        $.ajax({
            type: 'post',
            url: '/Booking/AjaxDeliveryAttachment',
            data: data,
            async: false,
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                if (response.Status != 0) {
                    Swal.fire({
                        title: 'Success',
                        text: response.Message,
                        icon: 'success'
                    }).then((result) => {
                        $('#attachmentModal').modal('hide');
                    });
                } else {
                    alert("Please select a file!");
                }
            },
            error: function (err) {
                alert(err.responseText);
            }
        });
        $("#load").load("/Booking/Documents?BookingNo=" + BookingNo);
    });

    function isClosed() {
        $('#attachmentModal').modal('hide');
        $("#load").load("/Booking/Documents?BookingNo=" + BookingNo);
    }
</script>