Controllers/CustomerBookings/CustomerDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BL = FutureTransportBuisenessLayer.CustomerBookings;
using BE = FutureTransportEntities.BusinessEntities;
using FutureTransport.Filters;

namespace FutureTransport.Controllers.CustomerBookings
{
    [UserAuthenticationFilter]
    public class CustomerDetailsController : Controller
    {
        BL.CustomerBookingsDataProvider DataProvider = new BL.CustomerBookingsDataProvider();

        public ActionResult CustomerBookings()
        {
            return View();
        }

        public JsonResult GetCustomerBookings(BE.Bookings CD)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetCustomerBookings(CD);
            return Json(list);
        }

        public ActionResult BookingDetails(string BookingNo)
        {
            ViewBag.BookingNo = BookingNo;
            return PartialView();
        }

        public JsonResult GetBookingDetails(string BN)
        {
            List<BE.Bookings> list = new List<BE.Bookings>();
            list = DataProvider.GetBookingDetails(BN);
            return Json(list);
        }
    }
}

Views/CustomerDetails/BookingDetails.cshtml
<div class="page-header">
    <h4 class="page-title">Booking Details</h4>
    <ol class="breadcrumb" id="IsDirect">
        <li class="breadcrumb-item">
            <a onclick="GetBack()" class="btn btn-primary btn-primary text-right" style="align-content:center;color:white" title="Back" data-toggle="tooltip" data-placement="bottom">
                <i class="fa fa-arrow-left"></i>
            </a>
        </li>
    </ol>
</div>

<div class="card wow zoomIn" data-wow-duration="1s" data-wow-delay="0.2s">
    <div class="card-body">
        <div class="row mt-5">
            <div class="col-6">
                <div class="form-group">
                    <div class="row">
                        <div class="col-4">
                            <label class="form-label mt-1">Booking No :</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            @Html.TextBox("BookingNo", null, new { @class = "form-control", @id = "BookingNo", name = "BookingNo", @Value = @ViewBag.BookingNo, @readonly = "readonly" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="table-responsive">
            <table class="th_Background table table-striped table-bordered text-center text-nowrap" style="width:100%" id="tblDetailsSummary">
                    <thead class="bg-primary">
                        <tr>
                            <th>Container Size</th>
                            <th>Container Type</th>
                            <th>Weight</th>
                            <th>Container No</th>
                            <th>Pickup Date</th>
                            <th>Dropoff Date</th>
                            <th>Driver</th>
                            <th>Vehicle</th>
                        </tr>
                    </thead>
                </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        LoadDetails();
    });

    function GetBack() {
        document.location = '@Url.Action("CustomerBookings", "CustomerDetails")';
    }

    function LoadDetails() {
        var BN = document.getElementById("BookingNo").value;

        var data = { 'BN': BN }
        data = JSON.stringify(data);

        $.ajax({
            url: "/CustomerDetails/GetBookingDetails",
            data: data,
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                ContainerM = response;
                $('#tblDetailsSummary').DataTable({
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": response,
                    "bPaginate": true,
                    "pageLength": 25,
                    "bInfo": true,
                    "paging": true,
                    order: [],
                    "searching": true,
                    "columns": [
                        { "data": "ContainerSize" },
                        { "data": "ContainerType" },
                        { "data": "Weight" },
                        {
                            "data": "ContainerNo",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.ContainerNo == "") {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.ContainerNo
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "PickUpDate",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.PickUpDate == "") {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.PickUpDate
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "DropOffDate",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.DropOffDate == "") {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.DropOffDate
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "Driver",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.Driver == "") {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.Driver
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "Vehicle",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.Vehicle == "") {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.Vehicle
                                    }
                                }
                                return data;
                            }
                        }
                    ],
                    mark: true
                });
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
    }
</script>

Views/CustomerDetails/CustomerBookings.cshtml
@{
    ViewBag.Title = "Customer Bookings";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<div id="CustomerBooking">
    <div class="page-header">
        <h4 class="page-title">Customer Bookings</h4>
    </div>

    <div class="card wow zoomIn" data-wow-duration="1s" data-wow-delay="0.2s">
        <div class="card-body">
            <div class="row no-gutters mt-5">
                <div class="col-md-2">
                    <div class="row no-gutters">
                        <div class="col-md-3">
                            <label class="form-label mt-2">From :</label>
                        </div>
                        <div class="col-md-7">
                            @Html.TextBox("From", null, new { @class = "form-control datePicker", @id = "fromS", name = "fromS", @Value = DateTime.Now.AddDays(-14).ToString("dd MMM yyyy") })
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="row no-gutters">
                        <div class="col-md-2">
                            <label class="form-label mt-2">To :</label>
                        </div>
                        <div class="col-md-7">
                            @Html.TextBox("To", null, new { @class = "form-control datePicker", @id = "toS", name = "toS", @Value = DateTime.Now.AddDays(1).ToString("dd MMM yyyy") })
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="row no-gutters">
                            <div class="col-md-5">
                                <label class="form-label mt-2">Shipment Type :</label>
                            </div>
                            <div class="col-md-5">
                                <select id="shipmentTypeS" class="form-control">
                                    <option value="I">Import</option>
                                    <option value="E">Export</option>
                                    <option value="0" selected>Both</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <div class="row no-gutters">
                            <div class="col-md-5">
                                <label class="form-label mt-2">Container Size :</label>
                            </div>
                            <div class="col-md-5">
                                <select id="containerSizeS" class="form-control">
                                    <option value="20">20</option>
                                    <option value="40">40</option>
                                    <option value="45">45</option>
                                    <option value="0" selected>ALL</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-warning" title="Search" data-toggle="tooltip" data-placement="bottom" onclick="Load()"><i class="fa fa-search"></i></button>
                </div>
            </div>

            <div class="table-responsive">
                <table class="th_Background table table-striped table-bordered text-center text-nowrap" style="width:100%" id="tblSummary">
                    <thead class="bg-primary">
                        <tr>
                            <th>Action</th>
                            <th>Booking No</th>
                            <th>Customer</th>
                            <th>Vendor Rate</th>
                            <th>Admin Rate</th>
                            <th>Booking Date & Time</th>
                            <th>20</th>
                            <th>40</th>
                            <th>45</th>
                            <th>PickUp Location</th>
                            <th>DropOff Location</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="Details"></div>

<script>
    $(document).ready(function () {
        Load();
    });

    $(function () {
        $(".datePicker").datepicker({
            autoclose: true,
            todayHighlight: true,
            format: 'dd M yyyy',
            language: "tr",
            changeMonth: true,
            changeYear: true,
        });
    });

    function Load() {
        var FromDate = document.getElementById("fromS").value;
        var ToDate = document.getElementById("toS").value;

        if (FromDate == "" || ToDate == "") {
            alert("Please select date range!");
            return false;
        }

        var date1 = new Date(FromDate);
        var date2 = new Date(ToDate);
        var Today = new Date();

        if (date1 >= date2) {
            document.getElementById('toS').style.borderColor = "red";
            Swal.fire({
                title: 'Error',
                text: "To date should not be less than from date!",
                icon: 'error'
            })
            return false;
        } else {
            document.getElementById('toS').style.borderColor = "Gainsboro";
        }

        var element = {};
        element.FromDate = document.getElementById("fromS").value;
        element.ToDate = document.getElementById("toS").value;
        element.ShipmentType = document.getElementById("shipmentTypeS").value;
        element.ContainerSize = document.getElementById("containerSizeS").value;

        var data = { 'CD': element }
        data = JSON.stringify(data);

        $.ajax({
            url: "/CustomerDetails/GetCustomerBookings",
            data: data,
            type: "POST",
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                $('#tblSummary').DataTable({
                    "destroy": true,
                    "bLengthChange": false,
                    "aaData": response,
                    "bPaginate": true,
                    "pageLength": 25,
                    "bInfo": true,
                    "paging": true,
                    order: [],
                    "searching": true,
                    "columns": [
                        {
                            "data": "BookingNo",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = "<div class=\"btn-group\" role=\"group\"><button class=\"btn btn-sm btn-primary mx-1\" title=\"View\" data-toggle=\"tooltip\" data-placement=\"bottom\" onclick=\"ShowDetails('" + row.BookingNo + "')\"><i class=\"fa fa-eye\"></i></button></div>"
                                }
                                return data;
                            }
                        },
                        { "data": "BookingNo" },
                        { "data": "CustomerName" },
                        {
                            "data": "Rate",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.Rate == 0) {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.Rate
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "ActualAmount",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.ActualAmount == 0) {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.ActualAmount
                                    }
                                }
                                return data;
                            }
                        },
                        { "data": "BookingDateTime" },
                        {
                            "data": "QuantityTwenty",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.QuantityTwenty == 0) {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.QuantityTwenty
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "QuantityFourty",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.QuantityFourty == 0) {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.QuantityFourty
                                    }
                                }
                                return data;
                            }
                        },
                        {
                            "data": "QuantityFourtyFive",
                            "orderable": false,
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    if (row.QuantityFourtyFive == 0) {
                                        data = "<div class=\"text-center\">-</div>"
                                    }
                                    else {
                                        data = row.QuantityFourtyFive
                                    }
                                }
                                return data;
                            }
                        },
                        { "data": "PickUpLocation" },
                        { "data": "DropOffLocation" }
                    ],
                    mark: true
                });
            },
            error: function (error) {
                alert(error.responseText);
            }
        });
    }

    function ShowDetails(BookingNo) {
        var data = { 'BookingNo': BookingNo };
        data = JSON.stringify(data);

        $.ajax({
            type: "POST",
            url: "/CustomerDetails/BookingDetails",
            data: data,
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                $('#CustomerBooking').hide();
                $('#Details').html(response);
                $('#Details').show();
            },
            failure: function (response) {
                alert(response);
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        })
    }
</script>